# Form implementation generated from reading ui file 'sports_5.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setStyleSheet("background-color: rgb(121,189,143);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 100, 471, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Tennis = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tennis.sizePolicy().hasHeightForWidth())
        self.Tennis.setSizePolicy(sizePolicy)
        self.Tennis.setMinimumSize(QtCore.QSize(50, 50))
        self.Tennis.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Tennis.setFont(font)
        self.Tennis.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"color: black")
        self.Tennis.setObjectName("Tennis")
        self.horizontalLayout.addWidget(self.Tennis)
        self.Football = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.Football.setMinimumSize(QtCore.QSize(50, 50))
        self.Football.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Football.setFont(font)
        self.Football.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"color: black")
        self.Football.setObjectName("Football")
        self.horizontalLayout.addWidget(self.Football)
        self.Bascketball = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.Bascketball.setMinimumSize(QtCore.QSize(50, 50))
        self.Bascketball.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Bascketball.setFont(font)
        self.Bascketball.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"color: black")
        self.Bascketball.setObjectName("Bascketball")
        self.horizontalLayout.addWidget(self.Bascketball)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(150, 200, 311, 91))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Volleyball = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.Volleyball.setMinimumSize(QtCore.QSize(50, 50))
        self.Volleyball.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Volleyball.setFont(font)
        self.Volleyball.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"color: black")
        self.Volleyball.setObjectName("Volleyball")
        self.horizontalLayout_2.addWidget(self.Volleyball)
        self.Hockey = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.Hockey.setMinimumSize(QtCore.QSize(50, 50))
        self.Hockey.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Hockey.setFont(font)
        self.Hockey.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"color: black")
        self.Hockey.setObjectName("Hockey")
        self.horizontalLayout_2.addWidget(self.Hockey)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tennis.setText(_translate("MainWindow", "Теннис"))
        self.Football.setText(_translate("MainWindow", "Футбол"))
        self.Bascketball.setText(_translate("MainWindow", "Баскетбол"))
        self.Volleyball.setText(_translate("MainWindow", "Воллейбол"))
        self.Hockey.setText(_translate("MainWindow", "Хоккей"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
